services:
    app-service:
        build: ./services/app/server
        ports:
            - "4002:4002"
        environment: 
          DATABASE_URL: "postgresql://postgres:Z0F62MLUEruNVw9q@db.vgbypelgjuuqgfclikkr.supabase.co:5432/postgres"
          REDISPASS: 'BYW3rmkjV4DeuxWLboyy2ef1JfWh9qyh'
          NODE_ENV: "production"
          PORT: 80
          JWT_SECRET: 'rahasia'
    user-service:
        build: ./services/users
        ports:
            - "4001:4001"
        environment: 
          DATABASE_URL: "postgresql://postgres:Z0F62MLUEruNVw9q@db.vgbypelgjuuqgfclikkr.supabase.co:5432/postgres"
          REDISPASS: 'BYW3rmkjV4DeuxWLboyy2ef1JfWh9qyh'
          NODE_ENV: "production"
          PORT: 80
          JWT_SECRET: 'rahasia'
    orchestrator:
        build: ./orchestratorGQL
        ports: 
            - "4000:4000"
        environment: 
          DATABASE_URL: "postgresql://postgres:Z0F62MLUEruNVw9q@db.vgbypelgjuuqgfclikkr.supabase.co:5432/postgres"
          REDISPASS: 'BYW3rmkjV4DeuxWLboyy2ef1JfWh9qyh'
          NODE_ENV: "production"
          PORT: 80
          JWT_SECRET: 'rahasia'