services:
    app-service:
        build: ./services/app/server
        ports:
            - "4002:4002"
        environment: 
          DATABASE_URL: "postgresql://postgres:Z0F62MLUEruNVw9q@db.vgbypelgjuuqgfclikkr.supabase.co:5432/postgres"
          NODE_ENV: "production"
    user-service:
        build: ./services/users
        ports:
            - "4001:4001"
     
  
   